#!/usr/bin/python
import sys
import csv

# To run this code on the actual data, please download the additional dataset.
# You can find instructions in the course materials (wiki) and in the instructor notes.
# There are some things in this data file that are different from what you saw
# in Lesson 3. The dataset is more complicated and closer to what you might
# see in the real world. It was generated by exporting data from a SQL database.
# 
# The data in at least one of the fields (the body field) can include newline
# characters, and all the fields are enclosed in double quotes. Therefore, we
# will need to process the data file in a way other than using split(","). To do this, 
# we have provided sample code for using the csv module of Python. Each 'line'
# will be a list that contains each field in sequential order.
# 
# In this exercise, we are interested in the field 'body' (which is the 5th field, 
# line[4]). The objective is to count the number of forum nodes where 'body' either 
# contains none of the three punctuation marks: period ('.'), exclamation point ('!'), 
# question mark ('?'), or 'body' contains exactly one such punctuation mark as the 
# last character. There is no need to parse the HTML inside 'body'. Also, do not pay
# special attention to newline characters.
def containsAny(str, set):
    for c in set:
        if c in str: 
            return True
    return False

def mapper(inputFile, outputFile):
    with open(inputFile,'rb') as tsvin, open(outputFile, 'wb') as csvout:
        reader = csv.reader(tsvin, delimiter='\t')
        writer = csv.writer(csvout, delimiter='\t', quotechar='"', quoting=csv.QUOTE_ALL)
        count = 0
        chars = set('.!?')
        for line in reader:
            if not containsAny(line[4], chars):
                writer.writerow(line)
                count += 1
            else:
                if not containsAny(line[4][0:len(line[4])-5], chars):  # Not taking into account </p>
                    writer.writerow(line)
                    count += 1
    return count

                
                
# This function allows you to test the mapper with the provided test string
def main():
    mapper('forum_node.tsv', 'forum_output.csv')

if __name__ == "__main__":
    main()